#include<stdio.h>
#include<stdlib.h>
#include<time.h>
int printRandoms(int l)
{
     int num=rand()%10 + l;
     printf("Number is ganerated.\n");
     return num;
}
 void guessNumber(int val)
 {
    int gus_no,chance=1;
    while(chance < 9) //No of chances: 8
       {
        printf("Now guess the number:-\n");
          scanf("%d",&gus_no);
        if(gus_no>val)
             { printf("You guess the larger number than the generated number.Please try again.\n"); chance++; }
        else if(gus_no<val)
             { printf("You guess the smaller number than the generated number.Please try again.\n"); chance++; }
        else if(gus_no==val)
             { printf("Congrats you win the challenge.\n"); break; }
        else { printf("Sorry you lose the game.\n");}
        }
 }
int main(void)
{
  printf("Welcome to the GUESS THE NUMBER challenge\nHere you have the guess the number between 1 t0 10 that should be generated by the system.\nIf you guess the number you win the challenge.\nNow get ready for the challenge.\n"); 
  srand(time(0));  //Seeding with Time
  int gen_no=printRandoms(1);
  guessNumber(gen_no);
  return 0;
}
